version: "3.9"
services:
  redis:
    image: redis:7.0.4-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
  filepoint:
    image: "filepoint"
    container_name: filepoint
    restart: unless-stopped
    depends_on:
      kafka:
        condition: service_healthy
    ports:
     - "${FILEPOINT_ADDR}:${FILEPOINT_ADDR}"
    build:
      context: .
      dockerfile: ./build/package/docker/Dockerfile
      args:
        - BINARY_NAME=filepoint
        - CONFIG_FILE=./config/config-docker.yaml
    volumes:
      - ./config:/app/config
  filepoint-webhooks-sender:
    image: "filepoint-webhooks-sender"
    container_name: filepoint-webhooks-sender
    restart: unless-stopped
    depends_on:
      kafka:
        condition: service_healthy
    build:
      context: .
      dockerfile: ./build/package/docker/Dockerfile
      args:
        - BINARY_NAME=filepoint-webhooks-sender
    volumes:
      - ./config:/app/config
