###
# Only use this if your .env PUBSUB setting is "kafka"
# docker compose -f docker-compose.yml -f docker-compose-kafka.yml up
###

version: "3.9"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: "zookeeper"
    restart: unless-stopped
    healthcheck:
      test: nc -z zookeeper 2181 || exit 1
      interval: 5s
      retries: 10
    ports:
      - 2181:2181
      - 2182:2182
    logging:
      driver: none
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: "kafka"
    restart: unless-stopped
    depends_on:
     zookeeper:
        condition: service_healthy
    healthcheck:
      test: nc -z kafka 9092 || exit -1
      start_period: 15s
      interval: 5s
      retries: 10
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENERS: INTERNAL://:9092,OUTSIDE://:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_MESSAGE_MAX_BYTES: 1048576
  control-center:
    image: confluentinc/cp-enterprise-control-center:7.5.0
    container_name: "control-center"
    hostname: control-center
    restart: unless-stopped
    depends_on:
      kafka:
        condition: service_healthy
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: "kafka:9092"
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      PORT: 9021
