Server:
  ReadTimeout: 10
  WriteTimeout: 10
  SSL: true
  CtxDefaultTimeout: 12
  Debug: true

Routes:
  upload:
    Topic: "filepoint_upload_queuing_dev"
    WebhookURL: "http://localhost:8000/filepoint-webhooks/upload"

AWSConfig:
  Bucket: "filepoint-us-dev"
  Region: "us-east-1"
  CloudfrontDist: "https://d1dczmkof7ci1q.cloudfront.net"
  VideoLabelingTopic: "arn:aws:sns:sa-east-1:029272547936:filepoint-video-labeling"
  RekognitionRole: "arn:aws:iam::526264782134:role/filepoint-rekognition-access"

KafkaConfig:
  Brokers:
    - "kafka:9092"
  MessagesPerSecond: 100
  MaxMessageBytes: 1048576
  MaxRetries: 10

SQSConfig:
  AWSRegion: "us-east-1"

RedisConfig:
  Addr: "redis:6379"
  MinIdleConns: 200
  PoolSize: 12000
  PoolTimeout: 240
  Username: ""
  Password: ""
