Server:
  ReadTimeout: 10
  WriteTimeout: 10
  SSL: true
  CtxDefaultTimeout: 12
  Debug: false

Aws:
  Endpoint: 127.0.0.1:9000
  AccessKey: aws
  SecretKey: 123
  UseSSL: false

Kafka:
  Brokers:
    - 'broker1'
  Topics:
    - 'topic1'

Redis:
  RedisAddr: redis:6379
  RedisPassword:
  RedisDb: 0
  RedisDefaultdb: 0
  MinIdleConns: 200
  PoolSize: 12000
  PoolTimeout: 240
  Password: ""
  DB: 0
