Server:
  ReadTimeout: 10
  WriteTimeout: 10
  SSL: true
  CtxDefaultTimeout: 12
  Debug: true

Routes:
  upload:
    TableName: "filepoint_upload"
    Topic: "filepoint_upload_queueing"
    PoisonTopic: "filepoint_upload_queueing_poison"
    WebhookURL: "http://webhook_site:80/d07d74d5-a5cd-4b5a-b44f-5a52e4f2e069" # http://webhook_site:8084/{{ your_unique_id }}
    MaxRetries: 50

AWSConfig:
  Endpoint: "http://localstack:4566" # if empty, will use AWS default endpoint.
  Bucket: "filepoint-us"
  Region: "us-east-1"
  CloudfrontCrtFile: "" # required if using AWS in production
  CloudfrontDist: "http://localhost:4566" # required if using AWS in production
  VideoLabelingTopic: "" # todo
  RekognitionRole: ""  # todo

StreamingConfig:
  MessagesPerSecond: 100
  KafkaConfig:
    Brokers:
      - "kafka:9092"
    MaxMessageBytes: 1048576
    MaxRetries: 50

RedisConfig:
  Addr: "redis:6379"
  MinIdleConns: 200
  PoolSize: 12000
  PoolTimeout: 240
  Username: ""
  Password: ""
