Server:
  ReadTimeout: 10
  WriteTimeout: 10
  SSL: true
  CtxDefaultTimeout: 12
  Debug: true

Routes:
  upload:
    Topic: "filepoint.upload.queuing"

AWSConfig:
  Bucket: "filepoint-us"
  Region: "us-east-1"
  CloudfrontDist: "https://d343c6r30h3w2g.cloudfront.net"
  VideoLabelingTopic: "arn:aws:sns:us-east-1:526264782134:filepoint-video-labeling"
  RekognitionRole: "arn:aws:iam::526264782134:role/filepoint-rekognition-access"

KafkaConfig:
  Brokers:
    - "kafka:9092"
  MessagesPerSecond: 100
  MaxMessageBytes: 1048576
  MaxRetries: 10

RedisConfig:
  Addr: "redis:6379"
  MinIdleConns: 200
  PoolSize: 12000
  PoolTimeout: 240
  Username: ""
  Password: ""
