Server:
  ReadTimeout: 10
  WriteTimeout: 10
  SSL: true
  CtxDefaultTimeout: 12
  Debug: true

Routes:
  upload:
    TableName: "filepoint_upload"
    Topic: "filepoint_upload_queueing"
    PoisonTopic: "filepoint_upload_queueing_poison"
    WebhookURL: "http://localhost:8000/filepoint-webhooks/upload"
    MaxRetries: 50

AWSConfig:
  Endpoint: "http://localstack:4566"
  Bucket: "filepoint-us"
  Region: "us-east-1"
  CloudfrontCrtFile: ".aws/filepoint-cloudfront.pem"
  CloudfrontDist: "https://d1dczmkof7ci1q.cloudfront.net"
  VideoLabelingTopic: "arn:aws:sns:sa-east-1:029272547936:filepoint-video-labeling"
  RekognitionRole: "arn:aws:iam::526264782134:role/filepoint-rekognition-access"

StreamingConfig:
  MessagesPerSecond: 100
  KafkaConfig:
    Brokers:
      - "kafka:9092"
    MaxMessageBytes: 1048576
    MaxRetries: 50

RedisConfig:
  Addr: "redis:6379"
  MinIdleConns: 200
  PoolSize: 12000
  PoolTimeout: 240
  Username: ""
  Password: ""
