Server:
  ReadTimeout: 10
  WriteTimeout: 10
  SSL: true
  CtxDefaultTimeout: 12
  Debug: true

Routes:
  upload:
    Topic: "filepoint.upload.queuing"
    WebhookURL: "https://webhook.site/724155e8-f99f-41f9-a235-7ebff3740cee"

AWSConfig:
  Bucket: "filepoint-us"
  Region: "us-east-1"
  CloudfrontDist: "https://d2srbzn4h1o9jv.cloudfront.net"
  VideoLabelingTopic: "arn:aws:sns:sa-east-1:029272547936:filepoint-video-labeling"
  RekognitionRole: "arn:aws:iam::526264782134:role/filepoint-rekognition-access"

KafkaConfig:
  Brokers:
    - "kafka:9092"
  MessagesPerSecond: 100
  MaxMessageBytes: 1048576
  MaxRetries: 10

RedisConfig:
  Addr: "redis:6379"
  MinIdleConns: 200
  PoolSize: 12000
  PoolTimeout: 240
  Username: ""
  Password: ""
