Server:
  ReadTimeout: 10
  WriteTimeout: 10
  SSL: true
  CtxDefaultTimeout: 12
  Debug: true

Routes:
  upload:
    TableName: "filepoint_upload"
    Topic: "filepoint_upload_queueing"
    PoisonTopic: "filepoint_upload_queueing_poison"
    WebhookURL: "http://localhost:8084/32c97faa-d306-41e3-b6cc-a3c438719d2a" # http://localhost:8084/{{ your_unique_id }}
    MaxRetries: 50

AWSConfig:
  Endpoint: "http://localhost:4566" # if empty, will use AWS default endpoint.
  Bucket: "filepoint-us"
  Region: "us-east-1"
  CloudfrontCrtFile: "" # optional, if not using AWS Cloundfront
  CloudfrontDist: "http://localhost:4566" # optional, if not using AWS Cloundfront
  VideoLabelingTopic: "" # todo
  RekognitionRole: ""  # todo

StreamingConfig:
  MessagesPerSecond: 100
  KafkaConfig:
    Brokers:
      - "localhost:9094"
    MaxMessageBytes: 1048576
    MaxRetries: 50

RedisConfig:
  Addr: "localhost:6379"
  MinIdleConns: 200
  PoolSize: 12000
  PoolTimeout: 240
  Username: ""
  Password: ""
