Server:
  ReadTimeout: 10
  WriteTimeout: 10
  SSL: true
  CtxDefaultTimeout: 12
  Debug: false

Routes:
  upload:
    Topic: "filepoint_upload_queuing"
    WebhookURL: "http://gearpoint.prod-gearpoint:8000/filepoint-webhooks/upload"

AWSConfig:
  Bucket: "filepoint-us"
  Region: "us-east-1"
  CloudfrontDist: "https://files.gearpoint.club"
  VideoLabelingTopic: "arn:aws:sns:sa-east-1:029272547936:filepoint-video-labeling"
  RekognitionRole: "arn:aws:iam::526264782134:role/filepoint-rekognition-access"

KafkaConfig:
  Brokers:
    - "localhost:9094"
  MessagesPerSecond: 100
  MaxMessageBytes: 1048576
  MaxRetries: 10

SQSConfig:
  AWSRegion: "us-east-1"

RedisConfig:
  Addr: "prod-elasticache.7g46gm.clustercfg.use1.cache.amazonaws.com:6379"
  MinIdleConns: 200
  PoolSize: 12000
  PoolTimeout: 240
  Username: ""
  Password: ""
