Server:
  ReadTimeout: 10
  WriteTimeout: 10
  SSL: true
  CtxDefaultTimeout: 12
  Debug: false

Routes:
  upload:
    TableName: "filepoint_upload"
    Topic: "filepoint_upload_queueing"
    PoisonTopic: "filepoint_upload_queueing_poison"
    WebhookURL: "https://api.gearpoint.club/filepoint-webhooks/upload"
    MaxRetries: 50

AWSConfig:
  Endpoint: ""
  Bucket: "filepoint-us"
  Region: "us-east-1"
  CloudfrontCrtFile: ".aws/filepoint-cloudfront.pem"
  CloudfrontDist: "https://files.gearpoint.club"
  VideoLabelingTopic: "arn:aws:sns:sa-east-1:029272547936:filepoint-video-labeling"
  RekognitionRole: "arn:aws:iam::526264782134:role/filepoint-rekognition-access"

StreamingConfig:
  MessagesPerSecond: 100
  KafkaConfig:
    Brokers:
      - "localhost:9094"
    MaxMessageBytes: 1048576
    MaxRetries: 50

RedisConfig:
  Addr: "prod-elasticache.7g46gm.clustercfg.use1.cache.amazonaws.com:6379"
  MinIdleConns: 200
  PoolSize: 12000
  PoolTimeout: 240
  Username: ""
  Password: ""
