basePath: /v1
definitions:
  http_utils.RestError:
    properties:
      description:
        items:
          type: string
        type: array
      message:
        type: string
    type: object
  views.GetSignedURLResponse:
    properties:
      expires:
        type: string
      labels:
        items:
          type: string
        type: array
      metadata:
        additionalProperties:
          type: string
        type: object
      temporary:
        type: boolean
      url:
        type: string
    type: object
  views.ListObjectsRequest:
    properties:
      prefixes:
        items:
          type: string
        type: array
    type: object
info:
  contact:
    email: luanbaggio0@gmail.com
    name: Luan Baggio
    url: https://github.com/luabagg
  description: Filepoint is the Gearpoint's file manager service.
  title: Filepoint
paths:
  /health:
    get:
      description: Returns a 200 OK response
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Health check
      tags:
      - HealthCheck
  /upload:
    delete:
      description: Deletes the file
      parameters:
      - description: File prefix
        in: query
        name: prefix
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          headers:
            X-Request-Id:
              description: Request ID (UUID)
              type: string
          schema:
            type: string
        "400":
          description: Bad Request
          headers:
            X-Request-Id:
              description: Request ID (UUID)
              type: string
          schema:
            $ref: '#/definitions/http_utils.RestError'
        "500":
          description: Internal Server Error
          headers:
            X-Request-Id:
              description: Request ID (UUID)
              type: string
      summary: Delete file
      tags:
      - Upload
    get:
      description: Returns the file signed URL
      parameters:
      - description: File prefix
        in: query
        name: prefix
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          headers:
            X-Request-Id:
              description: Request ID (UUID)
              type: string
          schema:
            $ref: '#/definitions/views.GetSignedURLResponse'
        "400":
          description: Bad Request
          headers:
            X-Request-Id:
              description: Request ID (UUID)
              type: string
          schema:
            $ref: '#/definitions/http_utils.RestError'
        "500":
          description: Internal Server Error
          headers:
            X-Request-Id:
              description: Request ID (UUID)
              type: string
      summary: Get file URL
      tags:
      - Upload
    post:
      consumes:
      - multipart/form-data
      description: Saves a file in the storage service and sends webhook.
      parameters:
      - description: User Identifier
        in: formData
        name: userId
        required: true
        type: string
      - description: File upload author
        in: formData
        name: author
        type: string
      - description: File title
        in: formData
        name: title
        type: string
      - description: File to be uploaded
        in: formData
        name: content
        required: true
        type: file
      produces:
      - application/json
      responses:
        "202":
          description: Accepted
          headers:
            Webhook-Request-Body:
              description: views.WebhookPayload{Id:"X-Request-Id", Success:true, Location:"{location}",
                Labels:[]string{}, Error:""}
              type: object
            X-Request-Id:
              description: Request ID (UUID)
              type: string
        "400":
          description: Bad Request
          headers:
            X-Request-Id:
              description: Request ID (UUID)
              type: string
          schema:
            $ref: '#/definitions/http_utils.RestError'
        "500":
          description: Internal Server Error
          headers:
            X-Request-Id:
              description: Request ID (UUID)
              type: string
      summary: File upload
      tags:
      - Upload
  /upload/all:
    delete:
      description: Deletes all files from prefix
      parameters:
      - description: File prefix
        in: query
        name: prefix
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          headers:
            X-Request-Id:
              description: Request ID (UUID)
              type: string
          schema:
            type: string
        "400":
          description: Bad Request
          headers:
            X-Request-Id:
              description: Request ID (UUID)
              type: string
          schema:
            $ref: '#/definitions/http_utils.RestError'
        "500":
          description: Internal Server Error
          headers:
            X-Request-Id:
              description: Request ID (UUID)
              type: string
      summary: Delete all
      tags:
      - Upload
  /upload/folder:
    get:
      description: Returns the files signed URLs
      parameters:
      - description: Folder prefix
        in: query
        name: prefix
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          headers:
            X-Request-Id:
              description: Request ID (UUID)
              type: string
          schema:
            items:
              $ref: '#/definitions/views.GetSignedURLResponse'
            type: array
        "400":
          description: Bad Request
          headers:
            X-Request-Id:
              description: Request ID (UUID)
              type: string
          schema:
            $ref: '#/definitions/http_utils.RestError'
        "500":
          description: Internal Server Error
          headers:
            X-Request-Id:
              description: Request ID (UUID)
              type: string
      summary: List files URLs
      tags:
      - Upload
  /upload/list:
    post:
      consumes:
      - application/json
      description: Returns the files signed URLs
      parameters:
      - description: prefixes
        in: body
        name: prefixes
        required: true
        schema:
          $ref: '#/definitions/views.ListObjectsRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          headers:
            X-Request-Id:
              description: Request ID (UUID)
              type: string
          schema:
            items:
              $ref: '#/definitions/views.GetSignedURLResponse'
            type: array
        "400":
          description: Bad Request
          headers:
            X-Request-Id:
              description: Request ID (UUID)
              type: string
          schema:
            $ref: '#/definitions/http_utils.RestError'
        "500":
          description: Internal Server Error
          headers:
            X-Request-Id:
              description: Request ID (UUID)
              type: string
      summary: List files URLs
      tags:
      - Upload
swagger: "2.0"
